### PR TITLE
Started Writing unit tests for ProjectService

### PR DESCRIPTION
**Pull request by ricardocarva**
Included Moq Library for mocking purposes in the SmartSprint.Test project
Created first three unit tests for the SmartSprint.Tests.Services.
Upgraded SmartSprint.Test project's dotnet version from 7.0 to 8.0.
Removed unnecessary file.

### CODE REVIEW

**Comment by ricardocarva** [comment]
@SWE-Martinez  Please have a look.

**Comment by ricardocarva** [comment]
Good sources to use to explore this topic:

1. https://medium.com/@codebob75/unit-testing-in-c-with-xunit-complete-guide-18ee2b919b05
2. https://medium.com/@jaydeepvpatil225/implementation-of-unit-test-using-xunit-and-moq-in-net-core-6-web-api-539205f1d38f
3.  https://learn.microsoft.com/en-us/ef/core/testing/testing-without-the-database
4. https://medium.com/multinetinventiv/dotnet6-integration-testing-with-sqlite-database-883d474f8257
5. https://victormagalhaes-dev.medium.com/test-coverage-analysis-with-coverlet-in-net-2e38df3c6ed7


The (1) is great to get your foot on the door and learn the basics with some examples.
The (2) is good as it shows how to write unit tests for controllers. I personally haven't had much success writing for controllers , and I think we should explore this. If you have some time, please go ahead and give it a try @SWE-Martinez 
(3) I have used the case here from this link where I used SQLite in-memory to mock the DB. The solution I implemented in that test case is new to me. We dont have this in my test case, but we may use this strategy if needed. The (4) may be useful in that case.
The (5) is something that I'd like to add to our project to generate reports based on code coverage. We should have some kind of requirement to have at least a certain % of our code covered by test cases.

**Comment by ricardocarva** [comment]
Created Wiki page on unit tests https://github.com/ricardocarva/AgileMinds/wiki/Unit-Tests.

**Review by thomas-martin-uf — APPROVED** [review]
looks good, thanks for adding this

**Pull request merged**
